name: big-bear-matterbridge
services:
  big-bear-matterbridge:
    container_name: big-bear-matterbridge
    image: luligu/matterbridge:3.9.4@sha256:6e2a0bcc14613842cc77fa697827bb280b68f23f51e26f467bb3f8cf768b6df5
    restart: unless-stopped
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/Matterbridge:/root/Matterbridge
    - /DATA/AppData/$AppID/.matterbridge:/root/.matterbridge
x-casaos:
  id: com.bigbeartechworld.matterbridge
  main: big-bear-matterbridge
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.matterbridge/assets/icon.png
  title:
    en_US: Matterbridge
  port_map: '8283'
