name: big-bear-matterbridge
services:
  big-bear-matterbridge:
    container_name: big-bear-matterbridge
    image: luligu/matterbridge:3.10.4@sha256:9d51990bf548e6e42a8a31fe86b6f677ffcab2f615422652551169d50182b02c
    restart: unless-stopped
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/Matterbridge:/root/Matterbridge
    - /DATA/AppData/$AppID/.matterbridge:/root/.matterbridge
x-casaos:
  id: com.bigbeartechworld.matterbridge
  main: big-bear-matterbridge
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.matterbridge/assets/icon.png
  title:
    en_US: Matterbridge
  port_map: '8283'
