name: big-bear-plex-nvidia
services:
  big-bear-plex-nvidia:
    container_name: big-bear-plex-nvidia
    image: linuxserver/plex:1.43.2@sha256:2785a6ad64d3a91529e31df678cf0f9fe8ddfe2718415222f270b8d1a6d765f0
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - VERSION=docker
    - PLEX_CLAIM=
    - CPU_FALLBACK=true
    - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/config
    - /DATA/AppData/$AppID/tv:/tv
    - /DATA/AppData/$AppID/movies:/movies
    devices:
    - /dev/dri:/dev/dri
    - /dev/dvb:/dev/dvb
    deploy:
      resources:
        reservations:
          memory: 256M
          devices:
          - capabilities:
            - gpu
x-casaos:
  id: com.bigbeartechworld.plex-nvidia
  main: big-bear-plex-nvidia
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.plex-nvidia/assets/icon.png
  title:
    en_US: Plex with NVIDIA GPU
  port_map: '32400'
