# Configuration for watchyourlan setup

# Name of the big-bear-watchyourlan application
name: big-bear-watchyourlan
# Service definitions for the big-bear-watchyourlan application
services:
  # Service name: big-bear-watchyourlan
  # The `big-bear-watchyourlan` service definition
  big-bear-watchyourlan:
    # Name of the container
    container_name: big-bear-watchyourlan
    # Image to be used for the container
    image: aceberg/watchyourlan:2.1.4@sha256:f77532ca7c3c9a4398cb094df7674013a3d7fcf4699386f1e456c24df6fef00e
    # Environment variables to be used for the container
    environment:
      - IFACES="eth0"
      - TZ="UTC"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-watchyourlan/data directory to /data/WatchYourLAN inside the container
      - /DATA/AppData/$AppID/data:/data/WatchYourLAN
    # Network mode to be used for the container
    network_mode: host
    x-casaos:
      envs:
        - container: IFACES
          description:
            en_US: 'Container Variable: IFACES'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /data/WatchYourLAN
          description:
            en_US: 'Container Path: /data/WatchYourLAN'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.watchyourlan
  # Main service for this application
  main: big-bear-watchyourlan
  # Detailed description for the application
  description:
    en_US: Lightweight network IP scanner. Can be used to notify about new hosts and monitor host online/offline history
  # Brief tagline for the application
  tagline:
    en_US: WatchYourLAN
  # Developer's information
  developer: ajnart
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/watchyourlan.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_US: WatchYourLAN
  # Category under which the application falls
  category: Networking
  # Default port mapping for the application
  port_map: "8840"
