name: big-bear-baserow
services:
  app:
    container_name: baserow
    image: baserow/baserow:2.3.2@sha256:bb2b366268e799aae84c98065ae984f18694940bcfa729eea51699fa621067ec
    environment:
      BASEROW_PUBLIC_URL: http://[YOUR_CASAOS_IP]:7350
    ports:
    - 7350:80
    - 7351:443
    volumes:
    - /DATA/AppData/$AppID/data:/baserow/data
x-casaos:
  id: com.bigbeartechworld.baserow
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.baserow/assets/icon.png
  title:
    en_US: Baserow
  port_map: '7350'
