name: big-bear-gotify
services:
  app:
    image: gotify/server:3.0.0@sha256:d75e89e0e28389c00c2556afe01282a37ee9756b0285799aa25214243aebd5e5
    ports:
    - 8091:80
    environment:
    - GOTIFY_DEFAULTUSER_NAME=admin
    - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
    - /DATA/AppData/$AppID/data:/app/data
    network_mode: bridge
x-casaos:
  id: com.bigbeartechworld.gotify
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.gotify/assets/icon.png
  title:
    en_US: Gotify
  port_map: '8091'
