name: big-bear-uptime-kuma
services:
  app:
    image: louislam/uptime-kuma:2@sha256:a8610b3b4c38077922ba51b036691e06887d7cefd91fe620fd3d6d23d03dc240
    container_name: uptime-kuma
    volumes:
    - /DATA/AppData/$AppID/data:/app/data
    ports:
    - 3001:3001
    restart: always
x-casaos:
  id: com.bigbeartechworld.uptime-kuma
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.uptime-kuma/assets/icon.png
  title:
    en_US: Uptime Kuma
  port_map: '3001'
