name: big-bear-filebrowser-quantum
services:
  app:
    container_name: big-bear-filebrowser-quantum
    image: gtstef/filebrowser:1.5.1-stable@sha256:e82e3bb6d03d4c9e6d5b6ded452b202f79bad335490889591580bf350b601133
    restart: unless-stopped
    environment:
    - TZ=UTC
    volumes:
    - /DATA/AppData/$AppID/data:/home/filebrowser/data
    - /DATA/AppData/$AppID/srv:/srv
    ports:
    - 8700:80
    networks:
    - big-bear-filebrowser-quantum-network
networks:
  big-bear-filebrowser-quantum-network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.filebrowser-quantum
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.filebrowser-quantum/assets/icon.png
  title:
    en_US: FileBrowser Quantum
  port_map: '8700'
