name: big-bear-tugtainer
services:
  big-bear-tugtainer:
    container_name: big-bear-tugtainer
    image: quenary/tugtainer:v1.30.9@sha256:bfecbbbb478dcdd0156324bf547bce1d0d0ec70b019167ea14b19f41c6214f5f
    restart: unless-stopped
    ports:
    - 9412:80
    environment:
      TZ: UTC
      LOG_LEVEL: warning
      JWT_SECRET_KEY: your-secret-key-here
      ACCESS_TOKEN_LIFETIME_MIN: '5'
      REFRESH_TOKEN_LIFETIME_MIN: '43200'
      HTTPS: 'FALSE'
    volumes:
    - /DATA/AppData/$AppID/data:/tugtainer
    - /var/run/docker.sock:/var/run/docker.sock
x-casaos:
  id: com.bigbeartechworld.tugtainer
  main: big-bear-tugtainer
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.tugtainer/assets/icon.png
  title:
    en_US: Tugtainer
  port_map: '9412'
