name: big-bear-ollama-cpu
services:
  big-bear-ollama-cpu:
    container_name: big-bear-ollama-cpu
    image: ollama/ollama:0.32.1@sha256:6345fbc18bd73a1e16404be681dbc6fd291a027cab43ed541abe78c4c81051b0
    restart: unless-stopped
    environment:
    - PORT=11434
    volumes:
    - /DATA/AppData/$AppID/.ollama:/root/.ollama
    ports:
    - 11434:11434
    devices:
    - /dev/kfd
    - /dev/dri
x-casaos:
  id: com.bigbeartechworld.ollama-cpu
  main: big-bear-ollama-cpu
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.ollama-cpu/assets/icon.png
  title:
    en_US: Ollama - CPU
  port_map: '11434'
