name: big-bear-ollama-cpu
services:
  big-bear-ollama-cpu:
    container_name: big-bear-ollama-cpu
    image: ollama/ollama:0.32.6@sha256:b88c73ace3e115f8ec53dc8761ae1c0aabfa675406e3681786b98757ce050f42
    restart: unless-stopped
    environment:
    - PORT=11434
    volumes:
    - /DATA/AppData/$AppID/.ollama:/root/.ollama
    ports:
    - 11434:11434
    devices:
    - /dev/kfd
    - /dev/dri
x-casaos:
  id: com.bigbeartechworld.ollama-cpu
  main: big-bear-ollama-cpu
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.ollama-cpu/assets/icon.png
  title:
    en_US: Ollama - CPU
  port_map: '11434'
