# Configuration for plex setup

# Name of the big-bear-plex application
name: big-bear-plex
# Service definitions for the big-bear-plex application
services:
  # Service name: big-bear-plex
  # The `big-bear-plex` service definition
  big-bear-plex:
    # Name of the container
    container_name: big-bear-plex
    # Image to be used for the container
    image: linuxserver/plex:1.43.3@sha256:59c671e182563040092a2d0901e429dc15e0aba9883acd13ef97857372b79b21
    environment:
      - PUID=1000 # specify the user id
      - PGID=1000 # specify the group id
      - TZ=Etc/UTC # specify a timezone to use.
      - VERSION=docker # Set whether to update plex or not.
      - PLEX_CLAIM= #optional Optionally you can obtain a claim token from https://plex.tv/claim and input here. Keep in mind that the claim tokens expire within 4 minutes.
    # Container restart policy
    restart: unless-stopped
    # Network mode for the container
    network_mode: host
    # Volumes to be mounted to the container
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/tv:/tv
      - /DATA/AppData/$AppID/movies:/movies
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
        - container: VERSION
          description:
            en_US: 'Container Variable: VERSION'
        - container: PLEX_CLAIM
          description:
            en_US: 'Container Variable: PLEX_CLAIM'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
        - container: /tv
          description:
            en_US: 'Container Path: /tv'
        - container: /movies
          description:
            en_US: 'Container Path: /movies'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.plex
  # Main service for this application
  main: big-bear-plex
  # Detailed description for the application
  description:
    en_US: Stream Movies & TV Shows
  # Brief tagline for the application
  tagline:
    en_US: Stream Movies & TV Shows
  # Developer's information
  developer: plexinc
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/plex.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_US: Plex
  # Category under which the application falls
  category: Media
  # Default port mapping for the application
  port_map: "32400"
