# Configuration for dockge setup

# Name of the big-bear-dockge application
name: big-bear-dockge
# Service definitions for the big-bear-dockge application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-dockge
    # Image to be used for the container
    image: louislam/dockge:1.5.0@sha256:335c6368b880ecc203236ed89e6e5232e0d6578e8ef5920e4a502390451502bf
    # Environment variables
    environment:
      # Tell Dockge where is your stacks directory
      DOCKGE_STACKS_DIR: "/DATA/AppData/big-bear-dockge/stacks"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/$AppID/data:/app/data
      - /DATA/AppData/$AppID/stacks:/DATA/AppData/big-bear-dockge/stacks
    # Ports mapping between host and container
    ports:
      - 5001:5001
    x-casaos:
      envs:
        - container: DOCKGE_STACKS_DIR
          description:
            en_US: 'Container Variable: DOCKGE_STACKS_DIR'
      volumes:
        - container: /var/run/docker.sock
          description:
            en_US: 'Container Path: /var/run/docker.sock'
        - container: /app/data
          description:
            en_US: 'Container Path: /app/data'
        - container: /DATA/AppData/big-bear-dockge/stacks
          description:
            en_US: 'Container Path: /DATA/AppData/big-bear-dockge/stacks'
      ports:
        - container: "5001"
          description:
            en_US: 'Container Port: 5001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.dockge
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: A fancy, easy-to-use and reactive docker `compose.yaml` stack-oriented manager
  # Brief tagline for the application
  tagline:
    en_US: Dockge
  # Developer's information
  developer: louislam
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/dockge.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_US: Dockge
  # Category under which the application falls
  category: Developer
  # Default port mapping for the application
  port_map: "5001"
