# Configuration for excalidraw setup

# Application Name
name: big-bear-excalidraw
# Services used in the application
services:
  # The `app` service for the excalidraw application
  app:
    # Name of the container
    container_name: big-bear-excalidraw
    # Docker image to be used
    image: excalidraw/excalidraw:latest@sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
    # Restart policy for the service
    restart: unless-stopped
    # Port mappings for the service
    ports:
      - "8000:80"
    x-casaos:
      ports:
        - container: "80"
          description:
            en_US: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.excalidraw
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Virtual whiteboard for sketching hand-drawn like diagrams
  # Brief tagline for the application
  tagline:
    en_US: Virtual whiteboard for sketching hand-drawn like diagrams
  # Developer's information
  developer: excalidraw
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/excalidraw/logo.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_US: Excalidraw
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "8000"
