name: big-bear-linuxserver-ungoogled-chromium
services:
  app:
    image: linuxserver/ungoogled-chromium:154.0.8037@sha256:96a033f6967576b41bf3597176ac45417daf52992b6a9090009fd1dbc64210f5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
        - container: CHROME_CLI
          description:
            en_US: 'Container Variable: CHROME_CLI'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.ungoogled-chromium
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Ungoogled Chromium is Google Chromium, sans dependency on Google web services.
  # Brief tagline for the application
  tagline:
    en_US: Google Chromium, sans dependency on Google web services.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/ungoogled-chromium-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/ungoogled-chromium-logo.png
  # Title for the application
  title:
    en_US: Ungoogled-chromium
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
