name: big-bear-gitea
services:
  big-bear-gitea:
    container_name: big-bear-gitea
    image: gitea/gitea:1.27.0@sha256:7dff60d7ea6df9d0bdf78971cdb1350e9b7df3fda5f115c77afe12122887bd64
    restart: unless-stopped
    ports:
    - 3000:3000
    - '2222:22'
    volumes:
    - /DATA/AppData/$AppID/data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__server__SSH_PORT=2222
    healthcheck:
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=3
      - --spider
      - http://localhost:3000
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
x-casaos:
  id: com.bigbeartechworld.gitea
  main: big-bear-gitea
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.gitea/assets/icon.png
  title:
    en_US: Gitea
  port_map: '3000'
