name: big-bear-mealie
services:
  app:
    container_name: big-bear-mealie
    image: hkotel/mealie:v3.22.0@sha256:36c28f0642fb6c75fae8997a2d55994631b9b4bcffba3016c208fc132a4c1e69
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/data:/app/data
    ports:
    - 9925:9000
x-casaos:
  id: com.bigbeartechworld.mealie
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.mealie/assets/icon.png
  title:
    en_US: Mealie
  port_map: '9925'
