name: big-bear-ntfy
services:
  app:
    image: binwiederhier/ntfy:v2.26.3@sha256:081b53dbb20674fcfe05fdb4eb8af9036a2645ef979543d16f7f80803af467b1
    command:
    - serve
    environment:
    - TZ=UTC
    ports:
    - target: 80
      published: '7200'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/cache:/var/cache/ntfy
    - /DATA/AppData/$AppID/config:/etc/ntfy
x-casaos:
  id: com.bigbeartechworld.ntfysh
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.ntfysh/assets/icon.png
  title:
    en_US: Ntfy.sh
  port_map: '7200'
