name: big-bear-ntfy
services:
  app:
    image: binwiederhier/ntfy:v2.27.0@sha256:f2419f405127afa868f10985c1a41449e673477cee1eb19994339a5ae8b592e7
    command:
    - serve
    environment:
    - TZ=UTC
    ports:
    - target: 80
      published: '7200'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/cache:/var/cache/ntfy
    - /DATA/AppData/$AppID/config:/etc/ntfy
x-casaos:
  id: com.bigbeartechworld.ntfysh
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.ntfysh/assets/icon.png
  title:
    en_US: Ntfy.sh
  port_map: '7200'
