name: big-bear-wishlist
services:
  big-bear-wishlist:
    container_name: big-bear-wishlist
    image: ghcr.io/cmintey/wishlist:v0.64.0@sha256:d2d189ec76f0f2d11864dca34183572900bedd72dd0594f18d639720409027d1
    restart: unless-stopped
    environment:
      ORIGIN: ''
      TOKEN_TIME: '72'
      DEFAULT_CURRENCY: USD
      LOG_LEVEL: info
    volumes:
    - /DATA/AppData/$AppID/uploads:/usr/src/app/uploads
    - /DATA/AppData/$AppID/data:/usr/src/app/data
    ports:
    - 3280:3280
x-casaos:
  id: com.bigbeartechworld.wishlist
  main: big-bear-wishlist
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.wishlist/assets/icon.png
  title:
    en_US: Wishlist
  port_map: '3280'
