name: big-bear-netalertx-v26
services:
  big-bear-netalertx-v26:
    container_name: big-bear-netalertx-v26
    image: jokobsk/netalertx:26.7.1@sha256:ffab3346b7a924b47bf6b992f369241801b736e54087011047e227937969532f
    restart: unless-stopped
    cap_drop:
    - ALL
    cap_add:
    - NET_RAW
    - NET_ADMIN
    - NET_BIND_SERVICE
    - CHOWN
    - SETUID
    - SETGID
    volumes:
    - /DATA/AppData/$AppID/config:/data/config
    - /DATA/AppData/$AppID/db:/data/db
    tmpfs:
    - /tmp
    environment:
    - TZ=UTC
    - PORT=8080
    - PUID=1000
    - PGID=1000
    - ALWAYS_FRESH_INSTALL=false
    network_mode: host
x-casaos:
  id: com.bigbeartechworld.netalertx-v26
  main: big-bear-netalertx-v26
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.netalertx-v26/assets/icon.png
  title:
    en_US: NetAlertX v26
  port_map: '8080'
