name: big-bear-portainer-agent
services:
  app:
    container_name: portainer-agent
    image: portainer/agent:2.44.0@sha256:2f8058d946a5dc8f70933afc06726e34de6d7f12a3fd5db1cf7987c327aea2d1
    network_mode: bridge
    ports:
    - 9001:9001
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes
x-casaos:
  id: com.bigbeartechworld.portainer-agent
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.portainer-agent/assets/icon.png
  title:
    en_US: Portainer Agent
  port_map: ''
