name: big-bear-owncloud
services:
  big-bear-owncloud:
    container_name: big-bear-owncloud
    image: owncloud/server:10.16.3@sha256:c2ab7775b5d28d52eb26a66059ef4d5dc7c8fb85aac718c471a2b4bba1047ec1
    restart: unless-stopped
    environment:
    - OWNCLOUD_DOMAIN=http://[YOUR_CASAOS_IP]:8080
    - OWNCLOUD_TRUSTED_DOMAINS=[YOUR_CASAOS_IP]
    - OWNCLOUD_DB_TYPE=mysql
    - OWNCLOUD_DB_NAME=big_bear_owncloud
    - OWNCLOUD_DB_USERNAME=bigbear
    - OWNCLOUD_DB_PASSWORD=f01914eb-2be3-4164-a57c-08e6518f313a
    - OWNCLOUD_DB_HOST=big-bear-owncloud-db
    - OWNCLOUD_ADMIN_USERNAME=bigbear
    - OWNCLOUD_ADMIN_PASSWORD=ed135299-7c80-48d4-a2a0-357a012213e5
    - OWNCLOUD_MYSQL_UTF8MB4=true
    - OWNCLOUD_REDIS_ENABLED=true
    - OWNCLOUD_REDIS_HOST=big-bear-owncloud-redis
    volumes:
    - /DATA/AppData/$AppID/data:/mnt/data
    ports:
    - 8080:8080
    networks:
    - big_bear_owncloud_network
    healthcheck:
      test:
      - CMD
      - /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
    - big-bear-owncloud-db
    - big-bear-owncloud-redis
  big-bear-owncloud-db:
    container_name: big-bear-owncloud-db
    image: mariadb:10.6@sha256:114d40be36852d0a019afd8458f7e1cc63fd300403b115b1f32e31130d5f671b
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=f01914eb-2be3-4164-a57c-08e6518f313a
    - MYSQL_USER=bigbear
    - MYSQL_PASSWORD=f01914eb-2be3-4164-a57c-08e6518f313a
    - MYSQL_DATABASE=big_bear_owncloud
    - MARIADB_AUTO_UPGRADE=1
    command:
    - --max-allowed-packet=128M
    - --innodb-log-file-size=64M
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -u
      - bigbear
      - --password=f01914eb-2be3-4164-a57c-08e6518f313a
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    networks:
    - big_bear_owncloud_network
  big-bear-owncloud-redis:
    container_name: big-bear-owncloud-redis
    image: redis:6.2.20@sha256:d06ff6ec778c7f2a5c0dfaf58141d598efaa50a89d0e966faedfdf122cef451b
    restart: unless-stopped
    command:
    - --databases
    - '1'
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - /DATA/AppData/$AppID/redis:/data
    networks:
    - big_bear_owncloud_network
networks:
  big_bear_owncloud_network:
    name: big_bear_owncloud_network
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.owncloud
  main: big-bear-owncloud
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.owncloud/assets/icon.png
  title:
    en_US: ownCloud
  port_map: '8080'
