name: big-bear-actual-server
services:
  app:
    image: actualbudget/actual-server:26.8.0@sha256:0b300f370dba85a74998a953736a831bd931cc8cb76c0d8ceac3d3fd288dfd4d
    container_name: actual-server
    volumes:
    - /DATA/AppData/$AppID:/data
    ports:
    - 5006:5006
    restart: unless-stopped
x-casaos:
  id: com.bigbeartechworld.actual-server
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.actual-server/assets/icon.png
  title:
    en_US: Actual Budget
  port_map: '5006'
