name: big-bear-linuxserver-embystat
services:
  app:
    image: linuxserver/embystat:0.2.0@sha256:adc479353fc0b810c21935a8fe3c2d20d9f7027edc9574477d702ec2ad414754
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6555
        published: 6555
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/embystat/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "6555"
          description:
            en_US: 'Container Port: 6555'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.embystat
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: 'Visit homepage: https://hub.docker.com/r/linuxserver/embystat/'
  # Brief tagline for the application
  tagline:
    en_US: A personal web server that can calculate all kinds of statistics from your (local) Emby server. Just install this on your server and let him calculate all kinds of fun stuff.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/embystat-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/embystat-logo.png
  # Title for the application
  title:
    en_US: Embystat
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "6555"
