name: big-bear-unifi-network-application
services:
  app:
    image: linuxserver/unifi-network-application:10.4.57@sha256:7d25457f8d0600388f663cd2316d7f86c8104de8e6fa9b6e2e44c7f6526476d6
    container_name: big-bear-unifi-network-application
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - MONGO_HOST=big-bear-unifi-db
    - MONGO_USER=unifi
    - MONGO_PASS=unifi_password
    - MONGO_PORT=27017
    - MONGO_DBNAME=unifi
    - MEM_LIMIT=1024
    - MEM_STARTUP=1024
    - MONGO_TLS=
    - MONGO_AUTHSOURCE=
    volumes:
    - /DATA/AppData/$AppID/config:/config
    ports:
    - 8443:8443
    - 3478:3478/udp
    - 10001:10001/udp
    - 8080:8080
    - 1900:1900/udp
    - 8843:8843
    - 8880:8880
    - 6789:6789
    - 5514:5514/udp
    restart: unless-stopped
    networks:
    - unifi-nework-application-network
    depends_on:
    - unifi-db
  unifi-db:
    image: mongo:6.0.11@sha256:52a007213974cab7753e9cd3fbd5750cc9a9f996f85ccdae73b164239b8f6951
    container_name: big-bear-unifi-db
    volumes:
    - /DATA/AppData/$AppID/db/data:/data/db
    - /DATA/AppData/$AppID/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
    - 27017:27017
    networks:
    - unifi-nework-application-network
    restart: unless-stopped
networks:
  unifi-nework-application-network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.unifi-network-application
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.unifi-network-application/assets/icon.png
  title:
    en_US: Unifi Network Application
  port_map: '8443'
