name: big-bear-nova-dso-tracker
services:
  nova:
    image: mrantonsg/nova-dso-tracker:6.2.2@sha256:1412e856855bce10147154ba207c11b904d3de50dbbfbb6a5fe0378a329620f0
    container_name: big-bear-nova-dso-tracker
    ports:
    - 5001:5001
    volumes:
    - /DATA/AppData/$AppID/instance:/app/instance
    restart: unless-stopped
    network_mode: bridge
x-casaos:
  id: com.bigbeartechworld.nova-dso-tracker
  main: nova
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.nova-dso-tracker/assets/icon.png
  title:
    en_US: Nova DSO Tracker
  port_map: '5001'
