name: big-bear-focalboard
services:
  app:
    container_name: big-bear-focalboard
    image: mattermost/focalboard:7.11.4@sha256:c935a2879dc7bcb8243a562afea21a30edbb6dbe029b53a9c0ae7ab4b3255c54
    restart: unless-stopped
    ports:
    - 8000:8000
    network_mode: bridge
    volumes:
    - /DATA/AppData/$AppID/data:/opt/focalboard/data
x-casaos:
  id: com.bigbeartechworld.focalboard
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.focalboard/assets/icon.png
  title:
    en_US: Focalboard
  port_map: '8000'
