name: big-bear-nextcloud
services:
  nextcloud:
    container_name: nextcloud
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:34.0.1@sha256:6ac8207d8b6b56ae903d3793c3a1c540bcb35911baa09d032b6ff514eef01084
    restart: unless-stopped
    ports:
    - 7580:80
    volumes:
    - /DATA/AppData/$AppID/html:/var/www/html
    environment:
    - POSTGRES_HOST=db-nextcloud
    - REDIS_HOST=redis-nextcloud
    - POSTGRES_PASSWORD=casaos
    - POSTGRES_USER=casaos
    - POSTGRES_DB=nextcloud
    - NEXTCLOUD_ADMIN_USER=casaos
    - NEXTCLOUD_ADMIN_PASSWORD=casaos
    - TRUSTED_PROXIES=
    - OVERWRITEPROTOCOL=http
    - PHP_MEMORY_LIMIT=1024M
    - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      db-nextcloud:
        condition: service_healthy
      redis-nextcloud:
        condition: service_healthy
    networks:
    - nextcloud_network
  db-nextcloud:
    container_name: db-nextcloud
    image: postgres:14.2@sha256:2c954f8c5d03da58f8b82645b783b56c1135df17e650b186b296fa1bb71f9cfd
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=casaos
    - POSTGRES_USER=casaos
    - POSTGRES_DB=nextcloud
    networks:
    - nextcloud_network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U casaos -d nextcloud
      interval: 10s
      timeout: 5s
      retries: 5
  redis-nextcloud:
    container_name: redis-nextcloud
    user: 1000:1000
    image: redis:6.2.20@sha256:d06ff6ec778c7f2a5c0dfaf58141d598efaa50a89d0e966faedfdf122cef451b
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/redis:/data
    networks:
    - nextcloud_network
    healthcheck:
      test:
      - CMD-SHELL
      - redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  cron:
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:34.0.1@sha256:6ac8207d8b6b56ae903d3793c3a1c540bcb35911baa09d032b6ff514eef01084
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      db-nextcloud:
        condition: service_healthy
      redis-nextcloud:
        condition: service_healthy
    networks:
    - nextcloud_network
networks:
  nextcloud_network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.nextcloud
  main: nextcloud
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.nextcloud/assets/icon.png
  title:
    en_US: Nextcloud
  port_map: '7580'
