name: big-bear-penpot
services:
  penpot-frontend:
    container_name: big-bear-penpot-frontend
    image: penpotapp/frontend:2.17.0@sha256:861989dfff50f12b9de1358c6b0f3cc1e601d7a678db2826f3643d0f93438500
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/assets:/opt/data/assets
    ports:
    - 9001:8080
    depends_on:
    - penpot-backend
    - penpot-exporter
    networks:
    - big-bear-penpot-network
  penpot-backend:
    image: penpotapp/backend:2.17.0@sha256:471cdebf185be899ef7d7593e9cd7994b908ebd7ffb78ca547e3d843bb83536f
    container_name: big-bear-penpot-backend
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/assets:/opt/data/assets
    depends_on:
    - penpot-postgres
    - penpot-redis
    networks:
    - big-bear-penpot-network
    environment:
    - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification
      disable-secure-session-cookies
    - PENPOT_SECRET_KEY=big-bear-penpot-secret-key
    - PENPOT_PUBLIC_URI=http://big-bear-penpot-frontend:8080
    - PENPOT_DATABASE_URI=postgresql://big-bear-penpot-postgres/penpot
    - PENPOT_DATABASE_USERNAME=bigbear
    - PENPOT_DATABASE_PASSWORD=casaos
    - PENPOT_REDIS_URI=redis://big-bear-penpot-redis/0
    - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
    - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
    - PENPOT_TELEMETRY_ENABLED=false
  penpot-exporter:
    image: penpotapp/exporter:2.17.0@sha256:7e8beb6ef2bdb9d778e9bbcbf7feebf8c99a137b2d9eb3969450c0a1a49e41c5
    container_name: big-bear-penpot-exporter
    restart: unless-stopped
    networks:
    - big-bear-penpot-network
    environment:
    - PENPOT_PUBLIC_URI=http://big-bear-penpot-frontend:8080
    - PENPOT_REDIS_URI=redis://big-bear-penpot-redis/0
  penpot-postgres:
    image: postgres:14@sha256:9e279cc7fc6e908da071befe389c576bd6752dbd295a9c078f96a75bab03e54c
    restart: unless-stopped
    container_name: big-bear-penpot-postgres
    stop_signal: SIGINT
    volumes:
    - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    networks:
    - big-bear-penpot-network
    environment:
    - POSTGRES_INITDB_ARGS=--data-checksums
    - POSTGRES_DB=penpot
    - POSTGRES_USER=bigbear
    - POSTGRES_PASSWORD=casaos
  penpot-redis:
    image: redis:7.4.6@sha256:d7432711a2a5c99c2e9dd0e006061cd274d7cb7a9e77f07ffe2ea99e21244677
    container_name: big-bear-penpot-redis
    restart: unless-stopped
    networks:
    - big-bear-penpot-network
  penpot-mailcatch:
    image: sj26/mailcatcher:latest@sha256:5d153a4daadf0c266f29c3856085741f06ca1e3768671f4267622d3e3ffe5564
    restart: always
    expose:
    - '1025'
    ports:
    - 1080:1080
    networks:
    - big-bear-penpot-network
networks:
  big-bear-penpot-network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.penpot
  main: penpot-frontend
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.penpot/assets/icon.jpg
  title:
    en_US: Penpot
  port_map: '9001'
