name: big-bear-linuxserver-mstream
services:
  app:
    image: linuxserver/mstream:6.28.1@sha256:0938777fbe4a1884aa7a24e8c203c39c22c8fc1a631c4330427725a8dae17e86
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mstream/config
        target: /config
      - type: bind
        source: /DATA/AppData/mstream/music
        target: /music
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
        - container: /music
          description:
            en_US: 'Container Path: /music'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.mstream
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Mstream is a personal music streaming server. You can use mStream to stream your music from your home computer to any device, anywhere. There are mobile apps available for both Android and iPhone.
  # Brief tagline for the application
  tagline:
    en_US: A personal music streaming server. You can use mStream to stream your music from your home computer to any device, anywhere. There are mobile apps available for both Android and iPhone.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/mstream-icon.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/mstream-icon.png
  # Title for the application
  title:
    en_US: Mstream
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
