name: big-bear-dockhand
services:
  app:
    container_name: big-bear-dockhand
    image: fnsys/dockhand:latest@sha256:c15530a672a0e5cf2d74229c9f0f2af5966ca144c22157ebc0075ffb929789e8
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /DATA/AppData/$AppID/data:/app/data
    ports:
    - 3003:3000
x-casaos:
  id: com.bigbeartechworld.dockhand
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dockhand/assets/icon.png
  title:
    en_US: Dockhand
  port_map: '3003'
