name: big-bear-code-server
services:
  app:
    image: linuxserver/code-server:4.129.0@sha256:076499743664cc7bac7fefe468860cd6949ad7ca247f20ffc1d4edefd2dc0956
    container_name: code-server
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=UTC
    - PASSWORD=my_password
    - SUDO_PASSWORD=sudo_my_password
    - DEFAULT_WORKSPACE=/config/workspace
    volumes:
    - /DATA/AppData/$AppID/config:/config
    - /DATA/AppData/$AppID/projects:/projects
    ports:
    - 8080:8443
    restart: always
x-casaos:
  id: com.bigbeartechworld.code-server
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.code-server/assets/icon.png
  title:
    en_US: Code Server
  port_map: '8080'
