name: big-bear-code-server
services:
  app:
    image: linuxserver/code-server:4.132.0@sha256:a6d1aa1083f224d1ebb47bf9e2eb9a5624c5107447014912b768c27bb30293fc
    container_name: code-server
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=UTC
    - PASSWORD=my_password
    - SUDO_PASSWORD=sudo_my_password
    - DEFAULT_WORKSPACE=/config/workspace
    volumes:
    - /DATA/AppData/$AppID/config:/config
    - /DATA/AppData/$AppID/projects:/projects
    ports:
    - 8080:8443
    restart: always
x-casaos:
  id: com.bigbeartechworld.code-server
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.code-server/assets/icon.png
  title:
    en_US: Code Server
  port_map: '8080'
