name: big-bear-linuxserver-vscodium
services:
  app:
    image: linuxserver/vscodium:1.135.06055@sha256:3a7e2ab355c744bcac49457fa01e184e35336eccdcf6192538a4b4d7c611c730
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.vscodium
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: VSCodium is a community-driven, freely-licensed binary distribution of Microsoft’s editor VS Code.
  # Brief tagline for the application
  tagline:
    en_US: A community-driven, freely-licensed binary distribution of Microsoft’s editor VS Code.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/vscodium-icon.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/vscodium-icon.png
  # Title for the application
  title:
    en_US: Vscodium
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
