name: big-bear-linuxserver-gitqlient
services:
  app:
    image: linuxserver/gitqlient:1.6.3@sha256:861b55c6e86c056b5543eeb2a88845f7b29b8b5386fa5d6bb9ca73eba21332b5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.gitqlient
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: GitQlient is a multi-platform Git client originally forked from QGit. Nowadays it goes beyond of just a fork and adds a lot of new functionality.
  # Brief tagline for the application
  tagline:
    en_US: A multi-platform Git client originally forked from QGit. Nowadays it goes beyond of just a fork and adds a lot of new functionality.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/gitqlient-icon.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/gitqlient-icon.png
  # Title for the application
  title:
    en_US: Gitqlient
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
