# Configuration for homebridge setup

# Name of the big-bear-homebridge application
name: big-bear-homebridge
# Service definitions for the big-bear-homebridge application
services:
  # Service name: big-bear-homebridge
  # The `big-bear-homebridge` service definition
  big-bear-homebridge:
    # Name of the container
    container_name: big-bear-homebridge
    # Image to be used for the container
    image: homebridge/homebridge:2024-05-02@sha256:ecdcb11b69a3c73e5c8e638a5f06ecd16d5212d8bdb52b58f1759f1fdcac6c9e
    # Container restart policy
    restart: unless-stopped
    # Environment Variables
    environment:
      - TZ=UTC # Timezone
    privileged: true
    network_mode: host
    # Volumes HOST:CONTAINER
    volumes:
      - /DATA/AppData/$AppID/data:/homebridge
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /homebridge
          description:
            en_US: 'Container Path: /homebridge'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.homebridge
  # Main service for this application
  main: big-bear-homebridge
  # Detailed description for the application
  description:
    en_US: HomeKit support for the impatient.
  # Brief tagline for the application
  tagline:
    en_US: HomeKit support for the impatient.
  # Developer's information
  developer: homebridge
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homebridge.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_US: HomeBridge
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "8581"
