name: big-bear-paperless-ngx
services:
  big-bear-paperless-ngx:
    container_name: big-bear-paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
    restart: unless-stopped
    environment:
      PAPERLESS_REDIS: redis://big-bear-paperless-ngx-broker:6379
      PAPERLESS_DBHOST: big-bear-paperless-ngx-db
      PAPERLESS_DBUSER: bigbear
      PAPERLESS_DBPASS: c6e74adb-3fce-4318-b657-4bdc0858fcac
      PAPERLESS_ADMIN_USER: bigbear
      PAPERLESS_ADMIN_PASSWORD: c22e92a6-2a3d-4edf-a98e-4044834daea6
      PAPERLESS_TIKA_ENABLED: 'true'
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://big-bear-paperless-ngx-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://big-bear-paperless-ngx-tika:9998
      PAPERLESS_URL: http://[YOUR_IP]:8000
      COMPOSE_PROJECT_NAME: big-bear-paperless-ngx
      PAPERLESS_CSRF_TRUSTED_ORIGINS: http://[YOUR_IP]:8000
    volumes:
    - /DATA/AppData/$AppID/paperless/data:/usr/src/paperless/data
    - /DATA/AppData/$AppID/paperless/media:/usr/src/paperless/media
    - /DATA/AppData/$AppID/paperless/export:/usr/src/paperless/export
    - /DATA/AppData/$AppID/paperless/consume:/usr/src/paperless/consume
    - /DATA/AppData/$AppID/paperless/tmp:/tmp
    ports:
    - 8000:8000
    depends_on:
    - big-bear-paperless-ngx-db
    - big-bear-paperless-ngx-broker
    networks:
    - big-bear-paperless-ngx-network
  big-bear-paperless-ngx-broker:
    container_name: big-bear-paperless-ngx-broker
    image: docker.io/library/redis:8.8.0@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/redis:/data
    networks:
    - big-bear-paperless-ngx-network
  big-bear-paperless-ngx-db:
    container_name: big-bear-paperless-ngx-db
    image: library/postgres:16@sha256:be01cf82fc7dbba824acf0a82e150b4b360f3ff93c6631d7844af431e841a95c
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: bigbear
      POSTGRES_PASSWORD: c6e74adb-3fce-4318-b657-4bdc0858fcac
    networks:
    - big-bear-paperless-ngx-network
  big-bear-paperless-ngx-gotenberg:
    container_name: big-bear-paperless-ngx-gotenberg
    image: gotenberg/gotenberg:8.34@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
    restart: unless-stopped
    command:
    - gotenberg
    - --chromium-disable-javascript=true
    - --chromium-allow-list=file:///tmp/.*
    networks:
    - big-bear-paperless-ngx-network
  big-bear-paperless-ngx-tika:
    container_name: big-bear-paperless-ngx-tika
    image: apache/tika:3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/tika/tmp:/tmp
    networks:
    - big-bear-paperless-ngx-network
networks:
  big-bear-paperless-ngx-network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.paperless-ngx
  main: big-bear-paperless-ngx
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.paperless-ngx/assets/icon.png
  title:
    en_US: Paperless-ngx
  port_map: '8000'
