name: big-bear-hrconvert2
services:
  app:
    image: dwaaan/hrconvert2-docker:latest
    ports:
      - target: 80
        published: 48113
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "80"
          description:
            en_US: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.hrconvert2
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: HRConvert2 is a self-hosted drag-and-drop file conversion server & file sharing tool that supports 86 file formats with 4 color schemes & 13 end-user selctable languages.
  # Screenshot links for the application
  screenshot_link:
    - https://github.com/zelon88/HRConvert2/raw/master/Documentation/Screenshots/HRConvert2-1.png
  # Brief tagline for the application
  tagline:
    en_US: HRConvert2 is a self-hosted drag-and-drop file conversion server & file sharing tool that supports 86 file formats with 4 color schemes & 13 end-user selctable languages.
  # Developer's information
  developer: zelon88
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/hrconvert2/logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/hrconvert2/logo.png
  # Title for the application
  title:
    en_US: HRConvert2
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "48113"
