name: big-bear-monica
services:
  big-bear-monica:
    container_name: big-bear-monica
    image: monica:4.1.2@sha256:f4e948060cf2ba9f304ed62de5c1e47035df91f0cb92f8cdbec924760f6735ae
    restart: unless-stopped
    environment:
    - APP_KEY=80356f7073c4f7834187b25a9d32cd2a
    - DB_HOST=big-bear-monica-db
    - DB_USERNAME=usermonica
    - DB_PASSWORD=passwordmonica
    volumes:
    - /DATA/AppData/$AppID/storage:/var/www/html/storage
    ports:
    - 8080:80
    networks:
    - big_bear_monica_network
  big-bear-monica-db:
    image: mariadb:10.6.11@sha256:efa2cc5bf16a2112ccb7e832f76d9e3913d017777b91293cd3e7c0d5e8286b23
    container_name: big-bear-monica-db
    environment:
    - TZ=UTC
    - MARIADB_RANDOM_ROOT_PASSWORD=true
    - MARIADB_DATABASE=monica
    - MARIADB_USER=usermonica
    - MARIADB_PASSWORD=passwordmonica
    volumes:
    - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
    - big_bear_monica_network
networks:
  big_bear_monica_network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.monica
  main: big-bear-monica
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.monica/assets/icon.png
  title:
    en_US: Monica
  port_map: '8080'
