name: big-bear-changedetection
services:
  big-bear-changedetection:
    container_name: big-bear-changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.55.3@sha256:2d0030e12494be9ebf6a6ebbbad46afe5763f498bbfefe9ebb7f0bf6be3ca5dc
    restart: unless-stopped
    ports:
    - 5000:5000
    volumes:
    - /DATA/AppData/$AppID/datastore:/datastore
x-casaos:
  id: com.bigbeartechworld.changedetection
  main: big-bear-changedetection
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.changedetection/assets/icon.png
  title:
    en_US: Change Detection
  port_map: '5000'
