name: big-bear-kiwix-serve
services:
  big-bear-kiwix-serve:
    container_name: big-bear-kiwix-serve
    image: ghcr.io/kiwix/kiwix-serve:3.7.0-2@sha256:9a19c082d0cf4a2bebc190e62d9f76980f18ea35ca3c9347197c5ed0ebaa08ce
    command: '*.zim'
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/zim:/data
    ports:
    - 8080:8080
x-casaos:
  id: com.bigbeartechworld.kiwix-serve
  main: big-bear-kiwix-serve
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.kiwix-serve/assets/icon.png
  title:
    en_US: Kiwix Server
  port_map: '8080'
