name: big-bear-nexterm
services:
  big-bear-nexterm:
    container_name: big-bear-nexterm
    image: nexterm/aio:1.2.2-BETA@sha256:def6f6a50b48c842d3fbe796ff8e7ce6b8fa54e2d92116a62742859c64f47d7e
    restart: unless-stopped
    environment:
    - ENCRYPTION_KEY=
    volumes:
    - /DATA/AppData/$AppID/data:/app/data
    ports:
    - 6989:6989
x-casaos:
  id: com.bigbeartechworld.nexterm
  main: big-bear-nexterm
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.nexterm/assets/icon.png
  title:
    en_US: Nexterm
  port_map: '6989'
