name: big-bear-linuxserver-vivaldi
services:
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:b5c17af7f4b5f9475302d9144b532ee5cbb57773a74bc307323c17f83cd0cd7c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
        - container: VIVALDI_CLI
          description:
            en_US: 'Container Variable: VIVALDI_CLI'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.vivaldi
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Vivaldi is a Norwegian freeware, cross-platform web browser with a built-in email client developed by Vivaldi Technologies.
  # Brief tagline for the application
  tagline:
    en_US: A Norwegian freeware, cross-platform web browser with a built-in email client developed by Vivaldi Technologies.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/vivaldi-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/vivaldi-logo.png
  # Title for the application
  title:
    en_US: Vivaldi
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
