name: big-bear-firefox
services:
  firefox:
    container_name: big-bear-firefox
    image: linuxserver/firefox:1152.0.5@sha256:d90c3bbaff5f4a0a1d0e24a65b2996e9bd940e137a6dbcfb1e78c4601313bba6
    ports:
    - 3000:3000
    - 3001:3001
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - FIREFOX_CLI=https://community.bigbeartechworld.com/
    shm_size: 1gb
    volumes:
    - /DATA/AppData/$AppID/config:/config
x-casaos:
  id: com.bigbeartechworld.firefox
  main: firefox
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.firefox/assets/icon.png
  title:
    en_US: Firefox
  port_map: '3000'
