name: big-bear-nextcloud-ls
services:
  big-bear-nextcloud-ls:
    container_name: big-bear-nextcloud-ls
    image: linuxserver/nextcloud:34.0.2@sha256:b7b489b4023ce51e043e586c60f730ab8d93fcf030b23e35ddeab83999a65cfa
    restart: unless-stopped
    ports:
    - 10443:443
    volumes:
    - /DATA/AppData/$AppID/config:/config
    - /DATA/AppData/$AppID/data:/data
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
x-casaos:
  id: com.bigbeartechworld.nextcloud-ls
  main: big-bear-nextcloud-ls
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.nextcloud-ls/assets/icon.png
  title:
    en_US: Nextcloud LS
  port_map: '10443'
