name: big-bear-linuxserver-qemu-static
services:
  app:
    image: linuxserver/qemu-static:10.0.2@sha256:3b35e71b380a231f8b649d5c14c00aa598bd87a99e2f5addc8388b8102532b34
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/qemu-static/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "80"
          description:
            en_US: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.qemu-static
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/qemu-static for details.
  # Brief tagline for the application
  tagline:
    en_US: This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/qemu-static for details.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/qemu-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/qemu-logo.png
  # Title for the application
  title:
    en_US: Qemu-static
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "80"
