name: big-bear-dozzle
services:
  app:
    container_name: big-bear-dozzle
    image: amir20/dozzle:v10.6.8@sha256:d282389858d23858cfe23882f9965d42145f370ac4abc021639efd95c3334336
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8888:8080
x-casaos:
  id: com.bigbeartechworld.dozzle
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dozzle/assets/icon.png
  title:
    en_US: Dozzle
  port_map: '8888'
