name: big-bear-dozzle
services:
  app:
    container_name: big-bear-dozzle
    image: amir20/dozzle:v10.6.14@sha256:1c1060cfb5402093c4e0f03f3534d7deaffeb0a6f6dd034e7c5f244603f35fb3
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8888:8080
x-casaos:
  id: com.bigbeartechworld.dozzle
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dozzle/assets/icon.png
  title:
    en_US: Dozzle
  port_map: '8888'
