name: big-bear-dozzle
services:
  app:
    container_name: big-bear-dozzle
    image: amir20/dozzle:v10.6.11@sha256:bc1ee4ba8d66c7fc0d03823a78486165fb219809f79eaf54cecf3114d647ab14
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8888:8080
x-casaos:
  id: com.bigbeartechworld.dozzle
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dozzle/assets/icon.png
  title:
    en_US: Dozzle
  port_map: '8888'
