name: big-bear-dozzle
services:
  app:
    container_name: big-bear-dozzle
    image: amir20/dozzle:v10.6.10@sha256:ea95d22b51f985564fdf22432b0c98fccf7c01653a51cf5403d39933d2724310
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8888:8080
x-casaos:
  id: com.bigbeartechworld.dozzle
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dozzle/assets/icon.png
  title:
    en_US: Dozzle
  port_map: '8888'
