# Configuration for octoprint setup

# Name of the big-bear-octoprint application
name: big-bear-octoprint
# Service definitions for the big-bear-octoprint application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: octoprint
    # Image to be used for the container
    image: octoprint/octoprint:1.11.8@sha256:5ea0181e476597faa2800c991af4ce16903005f46b4c16666a4080ad606310bb
    # Container restart policy
    restart: unless-stopped
    # devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
    #  - /dev/ttyACM0:/dev/ttyACM0
    #  - /dev/video0:/dev/video0
    volumes:
      - /DATA/AppData/$AppID/octoprint:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    #environment:
    #  - ENABLE_MJPG_STREAMER=true

    # Ports mapping between host and container
    ports:
      # Mapping port 7575 of the host to port 7575 of the container
      - "1080:80"
    x-casaos:
      volumes:
        - container: /octoprint
          description:
            en_US: 'Container Path: /octoprint'
      ports:
        - container: "80"
          description:
            en_US: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.octoprint
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: OctoPrint is the snappy web interface for your 3D printer!
  # Brief tagline for the application
  tagline:
    en_US: OctoPrint
  # Developer's information
  developer: octoprint
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/octoprint.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_US: OctoPrint
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "1080"
