name: big-bear-trilium
services:
  app:
    container_name: big-bear-trilium
    image: triliumnext/trilium:v0.104.0@sha256:8e053aa58a90c1690106a324a4692690ba0491c21ae40485b4051e2911df9489
    restart: unless-stopped
    environment:
    - TRILIUM_DATA_DIR=/home/node/trilium-data
    volumes:
    - /DATA/AppData/$AppID/data:/home/node/trilium-data
    ports:
    - 8080:8080
x-casaos:
  id: com.bigbeartechworld.trilium
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.trilium/assets/icon.png
  title:
    en_US: Trilium
  port_map: '8080'
