name: big-bear-portainer
services:
  app:
    container_name: big-bear-portainer
    image: portainer/portainer-ce:2.44.0-alpine@sha256:5376fd96f0bae14be7285ceb24c5cf9470dc23f19cdde74ff4c65d11cbe96eb2
    network_mode: bridge
    ports:
    - 8000:8000
    - 9000:9000
    - 9443:9443
    volumes:
    - /DATA/AppData/$AppID/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
x-casaos:
  id: com.bigbeartechworld.portainer
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.portainer/assets/icon.png
  title:
    en_US: Portainer
  port_map: '9443'
