name: big-bear-linuxserver-vlc
services:
  app:
    image: linuxserver/vlc:3.0.23@sha256:f7fa5bbd34c9283c96224c3571ce1cf4c4f2a7d9b98df531af2158fd2311f1bd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VLC_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vlc/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
        - container: VLC_CLI
          description:
            en_US: 'Container Variable: VLC_CLI'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.vlc
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: VLC Media Player is a free and open source cross-platform multimedia player and framework that delivers dependable performance across multiple devices.
  # Brief tagline for the application
  tagline:
    en_US: A free and open source cross-platform multimedia player and framework that delivers dependable performance across multiple devices.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/vlc-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/vlc-logo.png
  # Title for the application
  title:
    en_US: Vlc
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
