name: big-bear-2fauth
services:
  app:
    container_name: big-bear-2fauth
    image: 2fauth/2fauth:8.0.1@sha256:4a1f329e42b9bdfb625db3094bd6f79a2f44640b6259d4cdb9f336c676bf120e
    restart: unless-stopped
    ports:
    - 8000:8000
    network_mode: bridge
    volumes:
    - /DATA/AppData/$AppID/data:/2fauth
    environment:
    - APP_URL=http://[CHANGE_TO_LAN_IP]:8000
x-casaos:
  id: com.bigbeartechworld.2fauth
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.2fauth/assets/icon.png
  title:
    en_US: 2FAuth
  port_map: '8000'
