name: big-bear-dashy-v4
services:
  big-bear-dashy-v4:
    image: lissy93/dashy:4.0.8@sha256:1b3de6159d93e1a75f0b808e74d8cb5100c06251b120abd2d68e557ec7544ab6
    container_name: big-bear-dashy-v4
    volumes:
    - /DATA/AppData/$AppID/user-data:/app/user-data
    ports:
    - 4001:8080
    environment:
    - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - node
      - /app/services/healthcheck.js
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
x-casaos:
  id: com.bigbeartechworld.dashy-v4
  main: big-bear-dashy-v4
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dashy-v4/assets/icon.png
  title:
    en_US: Dashy v4
  port_map: '4001'
