name: big-bear-stalwart-mail
services:
  big-bear-stalwart-mail:
    container_name: big-bear-stalwart-mail
    image: stalwartlabs/stalwart:v0.16.16@sha256:66ae90f2753ec1dabd70f69cad7da9f0598d2628a04193ce2b08c7263d47aced
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/data:/opt/stalwart
    ports:
    - 8080:8080
    - 25:25/tcp
    - 143:143/tcp
    - 465:465/tcp
    - 587:587/tcp
    - 993:993/tcp
    - 4190:4190/tcp
x-casaos:
  id: com.bigbeartechworld.stalwart-mail
  main: big-bear-stalwart-mail
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.stalwart-mail/assets/icon.png
  title:
    en_US: Stalwart Mail
  port_map: '8080'
