name: big-bear-mosquitto
services:
  app:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
      - target: 9001
        published: 48114
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /mosquitto/config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /mosquitto/data
      - type: bind
        source: /DATA/AppData/$AppID/log
        target: /mosquitto/log
    x-casaos:
      volumes:
        - container: /mosquitto/config
          description:
            en_US: 'Container Path: /mosquitto/config'
        - container: /mosquitto/data
          description:
            en_US: 'Container Path: /mosquitto/data'
        - container: /mosquitto/log
          description:
            en_US: 'Container Path: /mosquitto/log'
      ports:
        - container: "1883"
          description:
            en_US: 'Container Port: 1883'
        - container: "9001"
          description:
            en_US: 'Container Port: 9001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - armv7
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.mosquitto
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Eclipse Mosquitto is an open source implementation of a server for versions 5, 3.1.1, and 3.1 of the MQTT protocol. You will need to create /portainer/Files/AppData/Config/Mosquitto/config/mosquitto.conf and if needed your password file. Have a look on https://mosquitto.org/man/mosquitto_passwd-1.html
  # Brief tagline for the application
  tagline:
    en_US: Eclipse Mosquitto Is An Open Source Implementation Of A Server For Versions 5, 3.1.1, And 3.1 Of The Mqtt Protocol. you Will Need To Create /portainer/files/appdata/config/mosquitto/config/mosquitto.conf And If Needed Your Password File. have A Look On Https://mosquitto.org/man/mosquitto_passwd-1.html
  # Developer's information
  developer: ""
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://raw.githubusercontent.com/docker-library/docs/757578e3a44e5460a8a11d32a81776f8b74231a9/eclipse-mosquitto/logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://raw.githubusercontent.com/docker-library/docs/757578e3a44e5460a8a11d32a81776f8b74231a9/eclipse-mosquitto/logo.png
  # Title for the application
  title:
    en_US: Eclipse Mosquitto
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "1883"
