name: big-bear-jlesage-firefox
services:
  big-bear-jlesage-firefox:
    container_name: big-bear-jlesage-firefox
    image: jlesage/firefox:v26.07.2@sha256:2bdbe30e355028eabb8a3a6f50a35a5d729e1de2376bc9c3c27c55fd2a7443d9
    ports:
    - 5800:5800
    environment:
    - VNC_PASSWORD=casaos
    - FF_OPEN_URL=https://community.bigbeartechworld.com/
    volumes:
    - /DATA/AppData/$AppID/config:/config
x-casaos:
  id: com.bigbeartechworld.jlesage-firefox
  main: big-bear-jlesage-firefox
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.jlesage-firefox/assets/icon.png
  title:
    en_US: Jlesage Firefox
  port_map: '5800'
