name: big-bear-ollama-nvidia
services:
  big-bear-ollama-nvidia:
    container_name: big-bear-ollama-nvidia
    image: ollama/ollama:0.32.3@sha256:ec24bcaa2a810eb74171ce7c517813ef4821ed678988845e8d76cf62467036d4
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/.ollama:/root/.ollama
    ports:
    - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
x-casaos:
  id: com.bigbeartechworld.ollama-nvidia
  main: big-bear-ollama-nvidia
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.ollama-nvidia/assets/icon.png
  title:
    en_US: Ollama - NVIDIA
  port_map: '11434'
