name: big-bear-retroarch-web
services:
  big-bear-retroarch-web:
    container_name: big-bear-retroarch-web
    image: inglebard/retroarch-web:latest@sha256:bf03014db81776a715b6289f017be2fc988688f9302590413cd6dcb615f07393
    restart: unless-stopped
    environment:
    - ROOT_WWW_PATH="/var/www/html"
    ports:
    - 8080:80
x-casaos:
  id: com.bigbeartechworld.retroarch-web
  main: big-bear-retroarch-web
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.retroarch-web/assets/icon.png
  title:
    en_US: RetroArch
  port_map: '8080'
