name: big-bear-wallos
services:
  big-bear-wallos:
    container_name: big-bear-wallos
    image: bellamy/wallos:4.9.6@sha256:3b2cdc843b4b1920220ce26a5804208eab8c236c60d4c777c6223c181f837be1
    restart: unless-stopped
    environment:
      TZ: UTC
    volumes:
    - /DATA/AppData/$AppID/db:/var/www/html/db
    - /DATA/AppData/$AppID/logos:/var/www/html/images/uploads/logos
    ports:
    - 8282:80
x-casaos:
  id: com.bigbeartechworld.wallos
  main: big-bear-wallos
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.wallos/assets/icon.png
  title:
    en_US: Wallos
  port_map: '8282'
