name: big-bear-wallos
services:
  big-bear-wallos:
    container_name: big-bear-wallos
    image: bellamy/wallos:5.4.2@sha256:316f26e13265958e7946ef98ff600516fddc51d698ee98bd1ae1577e5e00789f
    restart: unless-stopped
    environment:
      TZ: UTC
    volumes:
    - /DATA/AppData/$AppID/db:/var/www/html/db
    - /DATA/AppData/$AppID/logos:/var/www/html/images/uploads/logos
    ports:
    - 8282:80
x-casaos:
  id: com.bigbeartechworld.wallos
  main: big-bear-wallos
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.wallos/assets/icon.png
  title:
    en_US: Wallos
  port_map: '8282'
