name: big-bear-minio
services:
  app:
    image: bigbeartechworld/big-bear-minio:RELEASE.2025-10-15T17-29-55Z@sha256:7a18393957baa73bb4e3181e2e53b8b7051a99d7ce9a020bf76a58961f68c10f
    container_name: big-bear-minio
    volumes:
    - /DATA/AppData/$AppID:/data
    ports:
    - 9010:9000
    - 9011:9001
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    restart: unless-stopped
    command:
    - server
    - --console-address
    - :9001
    - /data
x-casaos:
  id: com.bigbeartechworld.minio
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.minio/assets/icon.png
  title:
    en_US: Minio
  port_map: '9011'
