name: big-bear-linuxserver-rustdesk
services:
  app:
    image: linuxserver/rustdesk:1.4.9@sha256:4e4d01107dcb3256ddf34b68f4f946171fa154352b433b454f77b95815d97216
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rustdesk/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.rustdesk
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: RustDesk is a full-featured open source remote control alternative for self-hosting and security with minimal configuration.
  # Brief tagline for the application
  tagline:
    en_US: A full-featured open source remote control alternative for self-hosting and security with minimal configuration.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/rustdesk-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/rustdesk-logo.png
  # Title for the application
  title:
    en_US: Rustdesk
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
