name: big-bear-morphos
services:
  big-bear-morphos:
    container_name: big-bear-morphos
    image: ghcr.io/danvergara/morphos-server:0.6.0@sha256:3d6f64ef386cbb6a7c5d55526e1a69da2d3661a1996d757897e92bf4369088f5
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/tmp:/tmp
    ports:
    - 8080:8080
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 30s
x-casaos:
  id: com.bigbeartechworld.morphos
  main: big-bear-morphos
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.morphos/assets/icon.png
  title:
    en_US: Morphos
  port_map: '8080'
