name: big-bear-mailpit
services:
  app:
    image: axllent/mailpit:v1.30@sha256:b868afa176bfd6cce2323ea316cd99ccad77915e51e595748f6d786700ecf109
    container_name: mailpit
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/data:/data
    environment:
    - TZ=UTC
    ports:
    - 8025:8025
    - 1025:1025
x-casaos:
  id: com.bigbeartechworld.mailpit
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.mailpit/assets/icon.png
  title:
    en_US: Mailpit
  port_map: '8025'
