name: big-bear-linuxserver-shotcut
services:
  app:
    image: linuxserver/shotcut:26.8.1@sha256:5bd6a0faccc7a1e1b1b1f09f13ae8c5646b0e426b5d76171b4f82558424847ce
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/shotcut/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "3000"
          description:
            en_US: 'Container Port: 3000'
        - container: "3001"
          description:
            en_US: 'Container Port: 3001'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.shotcut
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Shotcut is a free, open source, cross-platform video editor.
  # Brief tagline for the application
  tagline:
    en_US: A free, open source, cross-platform video editor.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/shotcut-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/shotcut-logo.png
  # Title for the application
  title:
    en_US: Shotcut
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "3000"
