name: big-bear-wg-easy-v15
services:
  big-bear-wg-easy-v15:
    container_name: big-bear-wg-easy-v15
    image: ghcr.io/wg-easy/wg-easy:15@sha256:93bbd593e07bab98d02807a28770ac87ab6c48818e319e68c1f66561feb99876
    restart: unless-stopped
    environment:
      INIT_ENABLED: 'true'
      INIT_USERNAME: bigbear
      INIT_PASSWORD: changeme
      INIT_HOST: '[YOUR_PUBLIC_IP]'
      INIT_PORT: '51820'
      INIT_DNS: 1.1.1.1,8.8.8.8
      INIT_IPV4_CIDR: 10.8.0.0/24
      INIT_IPV6_CIDR: fd42:42:42::/64
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.default.forwarding=1
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - /DATA/AppData/$AppID/data:/etc/wireguard
    ports:
    - 51820:51820/udp
    - 51821:51821/tcp
x-casaos:
  id: com.bigbeartechworld.wg-easy-v15
  main: big-bear-wg-easy-v15
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.wg-easy-v15/assets/icon.png
  title:
    en_US: WireGuard Easy v15
  port_map: '51821'
