name: big-bear-dashdot
services:
  app:
    image: mauricenino/dashdot:6.3.4@sha256:434a54d2937411a06b09c50e55709cc7d3b092c0fe173a9e5c986f9b5a33c7c6
    ports:
    - 3001:3001
    volumes:
    - /DATA/AppData/$AppID:/mnt/host
    privileged: true
x-casaos:
  id: com.bigbeartechworld.dashdot
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dashdot/assets/icon.png
  title:
    en_US: Dashdot
  port_map: '3001'
