name: big-bear-linuxserver-sealskin
services:
  app:
    image: linuxserver/sealskin:0.3.2@sha256:ca74767ab9b545860c30049a89d15f29061971c713952ba41673dcf8bfc969cd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOST_URL: ''
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
      - type: bind
        source: /DATA/AppData/sealskin/storage
        target: /storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
        - container: HOST_URL
          description:
            en_US: 'Container Variable: HOST_URL'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
        - container: /storage
          description:
            en_US: 'Container Path: /storage'
        - container: /var/run/docker.sock
          description:
            en_US: 'Container Path: /var/run/docker.sock'
      ports:
        - container: "8443"
          description:
            en_US: 'Container Port: 8443'
        - container: "8000"
          description:
            en_US: 'Container Port: 8000'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.sealskin
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: Sealskin is a self-hosted, client-server platform that enables users to run powerful, containerized desktop applications streamed directly to a web browser. It uses a browser extension to intercept user actions—such as clicking a link or downloading a file and redirects them to a secure, isolated application environment running on a remote server.
  # Brief tagline for the application
  tagline:
    en_US: A self-hosted, client-server platform that enables users to run powerful, containerized desktop applications streamed directly to a web browser. It uses a browser extension to intercept user actions—such as clicking a link or downloading a file and redirects them to a secure, isolated application environment running on a remote server.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/selkies-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/selkies-logo.png
  # Title for the application
  title:
    en_US: Sealskin
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "8443"
