name: big-bear-dbgate
services:
  big-bear-dbgate:
    container_name: big-bear-dbgate
    image: dbgate/dbgate:7.2.3-alpine@sha256:553a09bb9f861bea0de5196f0a6d07cdb5fb808509d79b6ddf9e930aa1c00722
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/config:/root/.dbgate
    ports:
    - 3000:3000
x-casaos:
  id: com.bigbeartechworld.dbgate
  main: big-bear-dbgate
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.dbgate/assets/icon.png
  title:
    en_US: DBGate
  port_map: '3000'
