name: big-bear-obsidian
services:
  big-bear-obsidian:
    container_name: big-bear-obsidian
    image: linuxserver/obsidian:1.13.6@sha256:30dc786853eb933ce187975db260ce68d344bd271a34c812d86bffd8e4e54ea0
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - /DATA/AppData/$AppID/config:/config
    ports:
    - 3000:3000
    - 3001:3001
x-casaos:
  id: com.bigbeartechworld.obsidian
  main: big-bear-obsidian
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.obsidian/assets/icon.png
  title:
    en_US: Obsidian
  port_map: '3000'
