name: big-bear-convertx
services:
  big-bear-convertx:
    container_name: big-bear-convertx
    image: ghcr.io/c4illin/convertx:v0.17.0@sha256:e1f85be04bbaf8a55ead9261194c3ae0fa0957d303ea537127154860b2552afd
    restart: unless-stopped
    ports:
    - 3000:3000
    environment:
    - JWT_SECRET=c8330437-e6ae-4cf0-9837-4d1326457e32
    - HTTP_ALLOWED=true
    volumes:
    - /DATA/AppData/$AppID/data:/app/data
x-casaos:
  id: com.bigbeartechworld.convertx
  main: big-bear-convertx
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.convertx/assets/icon.png
  title:
    en_US: ConvertX
  port_map: '3000'
