name: big-bear-faster-whisper
services:
  big-bear-faster-whisper:
    container_name: big-bear-faster-whisper
    image: linuxserver/faster-whisper:3.5.0@sha256:61c22ec203cea8ef62e1f9aeccb3d35364d6fcdac8a4cb808204df07d2e2e753
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - WHISPER_MODEL=tiny-int8
    - WHISPER_BEAM=1
    - WHISPER_LANG=en
    volumes:
    - /DATA/AppData/$AppID/config:/config
    ports:
    - 10300:10300
x-casaos:
  id: com.bigbeartechworld.faster-whisper
  main: big-bear-faster-whisper
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.faster-whisper/assets/icon.png
  title:
    en_US: Faster-whisper
  port_map: '7575'
