name: big-bear-davis
services:
  big-bear-davis:
    container_name: big-bear-davis
    image: ghcr.io/tchapi/davis-standalone:5.4.1@sha256:9db11b957fdce6d56c04185793c149b62db1596035feb876878acef6b3421be4
    restart: unless-stopped
    environment:
    - APP_ENV=prod
    - DATABASE_DRIVER=mysql
    - DATABASE_URL=mysql://bigbear:0c9d2acc-d4f3-423c-8361-86f35cdd3eb2@big-bear-davis-mysql:3306/davis?serverVersion=10.6.10&charset=utf8mb4
    - MAILER_DSN=smtp://:@big-bear-davis-mailpit:1025
    - ADMIN_LOGIN=bigbear
    - ADMIN_PASSWORD=aa9405b8-426c-41a1-bbc6-2924d8ec7eb3
    - AUTH_REALM=
    - AUTH_METHOD=
    - CALDAV_ENABLED=
    - CARDDAV_ENABLED=
    - WEBDAV_ENABLED=
    - WEBDAV_TMP_DIR=
    - WEBDAV_PUBLIC_DIR=
    - WEBDAV_HOMES_DIR=
    - INVITE_FROM_ADDRESS=
    - APP_TIMEZONE=UTC
    ports:
    - 9000:9000
    networks:
    - big-bear-davis-network
    depends_on:
    - big-bear-davis-mysql
    - big-bear-davis-mailpit
  big-bear-davis-mailpit:
    container_name: big-bear-davis-mailpit
    image: axllent/mailpit:v1.30@sha256:5a49a77c5bdbe7c5474450b4f46348d09949df3695257729c93a30369382d4f6
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/mailpit/data:/data
    environment:
    - TZ=UTC
    ports:
    - 8025:8025
    - 1025:1025
    networks:
    - big-bear-davis-network
  big-bear-davis-mysql:
    container_name: big-bear-davis-mysql
    image: mariadb:10.6.10@sha256:d1bd65504ffbea8dc7445223c9a9b1e6dc7d93f49f5ceff352bb9d43f52d0ffa
    environment:
    - MYSQL_ROOT_PASSWORD=0c9d2acc-d4f3-423c-8361-86f35cdd3eb2
    - MYSQL_DATABASE=davis
    - MYSQL_USER=bigbear
    - MYSQL_PASSWORD=0c9d2acc-d4f3-423c-8361-86f35cdd3eb2
    volumes:
    - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    networks:
    - big-bear-davis-network
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - localhost
      interval: 10s
      retries: 5
      timeout: 5s
networks:
  big-bear-davis-network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.davis
  main: big-bear-davis
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.davis/assets/icon.png
  title:
    en_US: Davis
  port_map: '9000'
