name: big-bear-otel-lgtm
services:
  big-bear-otel-lgtm:
    container_name: big-bear-otel-lgtm
    image: grafana/otel-lgtm:0.29.2@sha256:af7242c1a9608faf6d26e6f235392fd0c32b67258228f9a3cfc96e724974930c
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/data:/data
    ports:
    - mode: ingress
      target: 3000
      published: '3000'
      protocol: tcp
    - mode: ingress
      target: 4317
      published: '4317'
      protocol: tcp
    - mode: ingress
      target: 4318
      published: '4318'
      protocol: tcp
    networks:
    - big-bear-otel-lgtm
networks:
  big-bear-otel-lgtm:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.otel-lgtm
  main: big-bear-otel-lgtm
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.otel-lgtm/assets/icon
  title:
    en_US: OTEL LGTM
  port_map: '3000'
