name: big-bear-otel-lgtm
services:
  big-bear-otel-lgtm:
    container_name: big-bear-otel-lgtm
    image: grafana/otel-lgtm:0.29.0@sha256:6e14b923e0130b8b294ca5bcc7c94d54e899d150817e6c3ed82d9b665afe5499
    restart: unless-stopped
    volumes:
    - /DATA/AppData/$AppID/data:/data
    ports:
    - mode: ingress
      target: 3000
      published: '3000'
      protocol: tcp
    - mode: ingress
      target: 4317
      published: '4317'
      protocol: tcp
    - mode: ingress
      target: 4318
      published: '4318'
      protocol: tcp
    networks:
    - big-bear-otel-lgtm
networks:
  big-bear-otel-lgtm:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.otel-lgtm
  main: big-bear-otel-lgtm
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.otel-lgtm/assets/icon
  title:
    en_US: OTEL LGTM
  port_map: '3000'
