name: big-bear-linuxserver-socket-proxy
services:
  app:
    image: linuxserver/socket-proxy:3.4.4@sha256:ba211325155c463a1a6e6a038c928f21447a8e60ce02ecf41302047974097e84
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/socket-proxy/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "80"
          description:
            en_US: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.socket-proxy
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/socket-proxy for details.
  # Brief tagline for the application
  tagline:
    en_US: This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/socket-proxy for details.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/docker-logo.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/docker-logo.png
  # Title for the application
  title:
    en_US: Socket-proxy
  # Category under which the application falls
  category: Home
  # Default port mapping for the application
  port_map: "80"
