name: big-bear-write-freely
services:
  big-bear-write-freely:
    container_name: big-bear-write-freely
    image: nephatrine/write-freely:0.16@sha256:e2636c1a4d8e3010ff60cce8e5f861dff236056b99334be45d83c0e30c3e4d11
    restart: unless-stopped
    environment:
      TZ: UTC
      PUID: 1000
      PGID: 1000
    volumes:
    - /DATA/AppData/$AppID/data/config:/mnt/config
    ports:
    - 70:70/tcp
    - 8080:8080/tcp
x-casaos:
  id: com.bigbeartechworld.write-freely
  main: big-bear-write-freely
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.write-freely/assets/icon.png
  title:
    en_US: Write Freely
  port_map: '8080'
