name: big-bear-omada-controller
services:
  app:
    container_name: big-bear-omada-controller
    image: mbentley/omada-controller:6.2@sha256:03f19ddfddcb8415cca85dbc9a2506fd534c9127c94be2b19ba3a16b12899366
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
    - PUID=508
    - PGID=508
    - MANAGE_HTTP_PORT=8088
    - MANAGE_HTTPS_PORT=8043
    - PORTAL_HTTP_PORT=8088
    - PORTAL_HTTPS_PORT=8843
    - PORT_APP_DISCOVERY=27001
    - PORT_ADOPT_V1=29812
    - PORT_UPGRADE_V1=29813
    - PORT_MANAGER_V1=29811
    - PORT_MANAGER_V2=29814
    - PORT_DISCOVERY=29810
    - SHOW_SERVER_LOGS=true
    - SHOW_MONGODB_LOGS=false
    - SSL_CERT_NAME=tls.crt
    - SSL_KEY_NAME=tls.key
    - TZ=Etc/UTC
    volumes:
    - /DATA/AppData/$AppID/data:/opt/tplink/EAPController/data
    - /DATA/AppData/$AppID/logs:/opt/tplink/EAPController/logs
x-casaos:
  id: com.bigbeartechworld.tp-link-omada-controller
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.tp-link-omada-controller/assets/icon.png
  title:
    en_US: TP-Link Omada Controller
  port_map: '8088'
