name: big-bear-linuxserver-dillinger
services:
  app:
    image: linuxserver/dillinger:3.39.1@sha256:58dc39f6cddee732241c78f89805bca608299471f66ec90a8028e10b2cadd1b4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dillinger/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "8080"
          description:
            en_US: 'Container Port: 8080'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.dillinger
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: 'Visit homepage: https://hub.docker.com/r/linuxserver/dillinger/'
  # Brief tagline for the application
  tagline:
    en_US: A cloud-enabled, mobile-ready, offline-storage, AngularJS powered HTML5 Markdown editor.
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/dillinger.png
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/linuxserver/docker-templates@master/linuxserver.io/img/dillinger.png
  # Title for the application
  title:
    en_US: Dillinger
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "8080"
