name: big-bear-umbrel
services:
  big-bear-umbrel:
    container_name: big-bear-umbrel
    image: dockurr/umbrel:1.7.4@sha256:ae33fe21603853c4b8f90afb23493c98f550bfc601274bb74d1a4cadb0dade2e
    restart: unless-stopped
    ports:
    - 8080:80
    volumes:
    - /DATA/AppData/$AppID/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 1m
x-casaos:
  id: com.bigbeartechworld.umbrel-os
  main: big-bear-umbrel
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.umbrel-os/assets/icon.png
  title:
    en_US: Umbrel OS
  port_map: '8080'
