name: big-bear-linuxserver-python
services:
  app:
    image: linuxserver/python:3.14.7@sha256:a8c71ea50391142aad8e20e6b9bdb764b808ddb55b4fbe2abeb8a9ac150ee4d7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/python/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: 'Container Variable: PUID'
        - container: PGID
          description:
            en_US: 'Container Variable: PGID'
        - container: TZ
          description:
            en_US: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_US: 'Container Path: /config'
      ports:
        - container: "80"
          description:
            en_US: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - arm64
    - amd64
  # Stable reverse-domain app identifier
  id: com.bigbeartechworld.python
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_US: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/python for details.
  # Brief tagline for the application
  tagline:
    en_US: 'This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/python for details. '
  # Developer's information
  developer: LinuxServer.io
  # Author of this particular configuration
  author: WisdomSky
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@main/default-icon.svg
  # Thumbnail image for the application (if any)
  thumbnail: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@main/default-icon.svg
  # Title for the application
  title:
    en_US: Python
  # Category under which the application falls
  category: Others
  # Default port mapping for the application
  port_map: "80"
