name: big-bear-gladys
services:
  app:
    image: gladysassistant/gladys:v4.84.4@sha256:d04a665d2c5d008c6676bfa633611e80f2ef5675987778df2c7ddf4c6f0e4344
    restart: always
    privileged: true
    network_mode: host
    container_name: gladys
    cgroup: host
    environment:
      NODE_ENV: production
      SQLITE_FILE_PATH: /var/lib/gladysassistant/gladys-production.db
      TZ: Europe/Paris
      SERVER_PORT: '1080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /DATA/AppData/$AppID/data:/var/lib/gladysassistant
    - /dev:/dev
    - /run/udev:/run/udev
x-casaos:
  id: com.bigbeartechworld.gladys
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.gladys/assets/icon.png
  title:
    en_US: Gladys Assistant
  port_map: '1080'
