name: big-bear-lancache
services:
  app:
    image: lancachenet/monolithic:latest@sha256:c75ad2c9cdeb4f0608e6788e36ea9115b487bb95de482c4fbdf077b7caaa38ff
    environment:
    - USE_GENERIC_CACHE=true
    - LANCACHE_IP=10.0.39.1
    - DNS_BIND_IP=10.0.39.1
    - UPSTREAM_DNS=8.8.8.8
    - CACHE_ROOT=./lancache
    - CACHE_DISK_SIZE=2000g
    - CACHE_INDEX_SIZE=500m
    - CACHE_MAX_AGE=3650d
    - TZ=UTC
    restart: unless-stopped
    ports:
    - 8080:80
    - 10443:443
    volumes:
    - /DATA/AppData/$AppID/cache:/data/cache
    - /DATA/AppData/$AppID/logs:/data/logs
  dns:
    image: lancachenet/lancache-dns:latest@sha256:88b29d3979bef4b7b51868c4fcb3ab882f15c606ea010aa1b04c0b239df84001
    environment:
    - USE_GENERIC_CACHE=true
    - LANCACHE_IP=10.0.39.1
    - DNS_BIND_IP=10.0.39.1
    - UPSTREAM_DNS=8.8.8.8
    - CACHE_ROOT=./lancache
    - CACHE_DISK_SIZE=2000g
    - CACHE_INDEX_SIZE=500m
    - CACHE_MAX_AGE=3650d
    - TZ=UTC
    restart: unless-stopped
    ports:
    - 53:53/udp
    - 53:53/tcp
x-casaos:
  id: com.bigbeartechworld.lancache
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.lancache/assets/icon.png
  title:
    en_US: LAN Cache
  port_map: '8080'
