name: big-bear-unifi-network-application-mongo-4
services:
  app:
    image: linuxserver/unifi-network-application:10.4.57@sha256:30c19017c4f849ee4285cf7bcd0d3f292b0b6055735912c009d2a16c15319a51
    container_name: big-bear-unifi-network-application
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - MONGO_HOST=big-bear-unifi-db
    - MONGO_USER=unifi
    - MONGO_PASS=unifi_password
    - MONGO_PORT=27017
    - MONGO_DBNAME=unifi
    - MEM_LIMIT=1024
    - MEM_STARTUP=1024
    - MONGO_TLS=
    - MONGO_AUTHSOURCE=
    volumes:
    - /DATA/AppData/$AppID/config:/config
    ports:
    - 8443:8443
    - 3478:3478/udp
    - 10001:10001/udp
    - 8080:8080
    - 1900:1900/udp
    - 8843:8843
    - 8880:8880
    - 6789:6789
    - 5514:5514/udp
    restart: unless-stopped
    networks:
    - unifi-nework-application-network
    depends_on:
    - unifi-db
  unifi-db:
    image: mongo:4.4.28@sha256:7a272834036ddc9c7379c2d646b6a6c23c985e28c280f1340b3f611c762f9d83
    container_name: big-bear-unifi-db
    volumes:
    - /DATA/AppData/$AppID/db/data:/data/db
    - /DATA/AppData/big-bear-unifi-network-application/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
    - 27017:27017
    networks:
    - unifi-nework-application-network
    restart: unless-stopped
networks:
  unifi-nework-application-network:
    driver: bridge
x-casaos:
  id: com.bigbeartechworld.unifi-network-application-mongo-4
  main: app
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos@gh-pages/apps/com.bigbeartechworld.unifi-network-application-mongo-4/assets/icon.png
  title:
    en_US: Unifi Network Application
  port_map: '8443'
